ESGINI: /esg/config/esgcet/esg.ini
ant_dist_url: http://archive.apache.org/dist/ant/binaries/apache-ant-1.9.1-bin.tar.gz
ant_install_dir: /usr/local/ant
ant_min_version: 1.9.1
ant_version: 1.9.1
apache_frontend_repo: https://github.com/ESGF/apache-frontend.git
apache_frontend_version: v1.02
cdat_home: /usr/local/uvcdat/2.2.0
cdat_version: 2.2.0
certificate_extensions: pem|crt|cert|key
compress_extensions: .tar.gz|.tar.bz2|.tgz|.bz2|.tar
config_file: /esg/config/esgf.properties
date_format: +%Y_%m_%d_%H%M%S
db_database: esgcet
default_distinguished_name: OU=ESGF.ORG, O=ESGF
envfile: /etc/esg.env
error: !!python/object/apply:exceptions.IOError [2, No such file or directory, /esg/config/.esg_pg_publisher_pass]
esg_backup_dir: /esg/backups
esg_coffee_dist_url_root: distrib-coffee.ipsl.jussieu.fr/pub/esgf/dist
esg_config: !!python/object:__builtin__.file {}
esg_config_dir: /esg/config
esg_config_type_file: /esg/config/config_type
esg_dist_url_root: aims1.llnl.gov/esgf/dist
esg_etc_dir: /esg/etc
esg_installarg_file: /usr/local/bin/esg-installarg
esg_log_dir: /esg/log
esg_orp_version: 2.8.10
esg_root_dir: /esg
esg_search_version: 4.8.4
esg_testdir: /usr/local/src/esgf/workbench/esg/../esg_test
esg_tools_dir: /esg/tools
esgcet_egg_file: esgcet-3.0.1-py2.7.egg
esgcet_version: 3.0.1
esgf_coffee_dist_mirror: distrib-coffee.ipsl.jussieu.fr/pub/esgf
esgf_dashboard_db_version: '0.01'
esgf_dashboard_ip_workdir: /usr/local/src/esgf/workbench/esg/esgf-dashboard-ip
esgf_dashboard_version: 1.3.18
esgf_desktop_version: 0.0.20
esgf_dist_mirror: aims1.llnl.gov/esgf
esgf_idp_version: 2.7.2
esgf_node_manager_db_version: 0.1.5
esgf_node_manager_version: 0.7.16
esgf_secret_file: /esg/config/.esgf_pass
esgf_security_db_version: 0.1.5
esgf_security_version: 2.7.6
esgf_web_fe_version: 2.6.5
force_install: false
globus_global_certs_dir: /etc/grid-security/certificates
globus_location: /usr/local/globus
index_config: master slave
install_manifest: /esg/esgf-install-manifest
install_prefix: /usr/local
installer_gid: 20
installer_home: /usr/local/src/esgf
installer_uid: 501
installer_user: williamhill
java_dist_url: aims1.llnl.gov/esgf/dist/java/1.8.0_131/jdk1.8.0_131-64.tar.gz
java_install_dir: /usr/local/java
java_min_version: 1.8.0_131
java_opts: ''
java_rpm_url: aims1.llnl.gov/esgf/dist/java/1.8.0_112/jdk-8u131-linux-x64.rpm
java_version: 1.8.0_131
keystore_alias: my_esgf_node
keystore_file: /esg/config/tomcat/keystore-tomcat
keystore_password: ''
ks_secret_file: /esg/config/.esg_keystore_pass
mail_admin_address: ''
mail_smtp_host: smtp.local
myLD_LIBRARY_PATH: /usr/local/openssl/lib:/usr/local/uvcdat/2.2.0/Externals/lib:/usr/local/globus/lib:/usr/local/geoip/lib:/usr/lib64:/usr/lib
myPATH: /usr/local/openssl/bin:/usr/local/java/bin:/usr/local/ant/bin:/usr/local/uvcdat/2.2.0/bin:/usr/local/uvcdat/2.2.0/Externals/bin:/usr/local/tomcat/bin:/usr/local/globus/bin:/usr/local/bin:/sbin:/usr/bin:/usr/sbin
no_globus: false
node_db_name: esgcet
num_backups_to_keep: '7'
number_of_cpus: 4
openssl_dist_url: http://www.openssl.org/source/openssl-/0.9.8r/.tar.gz
openssl_install_dir: /usr/local/openssl
openssl_max_version: 0.9.9z
openssl_min_version: 0.9.8e
openssl_version: 0.9.8r
openssl_workdir: /usr/local/src/esgf/workbench/esg/openssl
pg_secret_file: /esg/config/.esg_pg_pass
pg_sys_acct: postgres
pg_sys_acct_group: postgres
pg_sys_acct_passwd: changeme
postgress_bin_dir: /usr/bin
postgress_driver: org.postgresql.Driver
postgress_host: localhost
postgress_install_dir: /var/lib/pgsql
postgress_jar: postgresql-8.4-703.jdbc3.jar
postgress_lib_dir: /usr/lib64/pgsql
postgress_min_version: 8.4.20
postgress_port: '5432'
postgress_protocol: 'jdbc:postgresql:'
postgress_user: dbsuper
postgress_version: 8.4.20
pub_secret: ''
pub_secret_file: /esg/config/.esg_pg_publisher_pass
publisher_config: esg.ini
publisher_db_user_passwd: ''
publisher_home: /esg/config/esgcet
publisher_repo: git://github.com/ESGF/esg-publisher.git
publisher_repo_https: https://github.com/ESGF/esg-publisher.git
publisher_tag: v3.0.1
python_version: '2.7'
scripts_dir: /usr/local/bin
show_summary_latch: 0
source_latch: '0'
tds_min_version: 5.0.0
tds_version: 5.0.0
thredds_content_dir: /esg/content
thredds_replica_dir: /esg/data/replica
thredds_root_dir: /esg/data
tomcat_conf_dir: /esg/config/tomcat
tomcat_dist_url: http://archive.apache.org/dist/tomcat/tomcat-8/v8.5.9/bin/apache-tomcat-8.5.9.tar.gz
tomcat_group: tomcat
tomcat_http_path: http://archive.apache.org/dist/tomcat/tomcat
tomcat_install_dir: /usr/local/tomcat
tomcat_major_version: '8'
tomcat_min_version: 8.5.9
tomcat_opts: ''
tomcat_pid_file: /var/run/tomcat-jsvc.pid
tomcat_user: tomcat
tomcat_users_file: /esg/config/tomcat/tomcat-users.xml
tomcat_version: 8.5.9
truststore_file: /esg/config/tomcat/esg-truststore.ts
truststore_password: changeit
word_size: '64'
workdir: /usr/local/src/esgf/workbench/esg
